# Generated by rust2rpm-9-1.fc31
%bcond_with check
%global debug_package %{nil}

%global crate object

Name:           rust-%{crate}
Version:        0.25.3
Release:        1
Summary:        Unified interface for parsing object file formats

# Upstream license specification: Apache-2.0/MIT
License:        ASL 2.0 or MIT
URL:            https://crates.io/crates/object
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
BuildRequires:  (crate(flate2/default) >= 1.0.0 with crate(flate2/default) < 2.0.0)
BuildRequires:  (crate(goblin/archive) >= 0.0.22 with crate(goblin/archive) < 0.0.23)
BuildRequires:  (crate(goblin/elf32) >= 0.0.22 with crate(goblin/elf32) < 0.0.23)
BuildRequires:  (crate(goblin/elf64) >= 0.0.22 with crate(goblin/elf64) < 0.0.23)
BuildRequires:  (crate(goblin/endian_fd) >= 0.0.22 with crate(goblin/endian_fd) < 0.0.23)
BuildRequires:  (crate(goblin/mach32) >= 0.0.22 with crate(goblin/mach32) < 0.0.23)
BuildRequires:  (crate(goblin/mach64) >= 0.0.22 with crate(goblin/mach64) < 0.0.23)
BuildRequires:  (crate(goblin/pe32) >= 0.0.22 with crate(goblin/pe32) < 0.0.23)
BuildRequires:  (crate(goblin/pe64) >= 0.0.22 with crate(goblin/pe64) < 0.0.23)
BuildRequires:  (crate(goblin/std) >= 0.0.22 with crate(goblin/std) < 0.0.23)
BuildRequires:  (crate(parity-wasm/default) >= 0.38.0 with crate(parity-wasm/default) < 0.39.0)
BuildRequires:  (crate(scroll) >= 0.9.0 with crate(scroll) < 0.10.0)
BuildRequires:  (crate(uuid) >= 0.7.0 with crate(uuid) < 0.8.0)
%if %{with check}
BuildRequires:  (crate(memmap/default) >= 0.7.0 with crate(memmap/default) < 0.8.0)
%endif

%global _description \
A unified interface for parsing object file formats.

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE-APACHE LICENSE-MIT
%doc README.md
%{cargo_registry}/%{crate}-%{version}/
%exclude %{cargo_registry}/%{crate}-%{version}/coverage

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+compression-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+compression-devel %{_description}

This package contains library source intended for building other packages
which use "compression" feature of "%{crate}" crate.

%files       -n %{name}+compression-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+flate2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+flate2-devel %{_description}

This package contains library source intended for building other packages
which use "flate2" feature of "%{crate}" crate.

%files       -n %{name}+flate2-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+parity-wasm-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+parity-wasm-devel %{_description}

This package contains library source intended for building other packages
which use "parity-wasm" feature of "%{crate}" crate.

%files       -n %{name}+parity-wasm-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages
which use "std" feature of "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+wasm-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+wasm-devel %{_description}

This package contains library source intended for building other packages
which use "wasm" feature of "%{crate}" crate.

%files       -n %{name}+wasm-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif
