# Generated by rust2rpm-9-1.fc31
%bcond_with check
%global debug_package %{nil}

%global crate object

Name:           rust-%{crate}
Version:        0.12.0
Release:        3%{?dist}
Summary:        Unified interface for parsing object file formats

# Upstream license specification: Apache-2.0/MIT
License:        ASL 2.0 or MIT
URL:            https://crates.io/crates/object
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
BuildRequires:  (crate(flate2/default) >= 1.0.0 with crate(flate2/default) < 2.0.0)
BuildRequires:  (crate(goblin/archive) >= 0.0.22 with crate(goblin/archive) < 0.0.23)
BuildRequires:  (crate(goblin/elf32) >= 0.0.22 with crate(goblin/elf32) < 0.0.23)
BuildRequires:  (crate(goblin/elf64) >= 0.0.22 with crate(goblin/elf64) < 0.0.23)
BuildRequires:  (crate(goblin/endian_fd) >= 0.0.22 with crate(goblin/endian_fd) < 0.0.23)
BuildRequires:  (crate(goblin/mach32) >= 0.0.22 with crate(goblin/mach32) < 0.0.23)
BuildRequires:  (crate(goblin/mach64) >= 0.0.22 with crate(goblin/mach64) < 0.0.23)
BuildRequires:  (crate(goblin/pe32) >= 0.0.22 with crate(goblin/pe32) < 0.0.23)
BuildRequires:  (crate(goblin/pe64) >= 0.0.22 with crate(goblin/pe64) < 0.0.23)
BuildRequires:  (crate(goblin/std) >= 0.0.22 with crate(goblin/std) < 0.0.23)
BuildRequires:  (crate(parity-wasm/default) >= 0.38.0 with crate(parity-wasm/default) < 0.39.0)
BuildRequires:  (crate(scroll) >= 0.9.0 with crate(scroll) < 0.10.0)
BuildRequires:  (crate(uuid) >= 0.7.0 with crate(uuid) < 0.8.0)
%if %{with check}
BuildRequires:  (crate(memmap/default) >= 0.7.0 with crate(memmap/default) < 0.8.0)
%endif

%global _description \
A unified interface for parsing object file formats.

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE-APACHE LICENSE-MIT
%doc README.md
%{cargo_registry}/%{crate}-%{version}/
%exclude %{cargo_registry}/%{crate}-%{version}/coverage

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+compression-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+compression-devel %{_description}

This package contains library source intended for building other packages
which use "compression" feature of "%{crate}" crate.

%files       -n %{name}+compression-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+flate2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+flate2-devel %{_description}

This package contains library source intended for building other packages
which use "flate2" feature of "%{crate}" crate.

%files       -n %{name}+flate2-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+parity-wasm-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+parity-wasm-devel %{_description}

This package contains library source intended for building other packages
which use "parity-wasm" feature of "%{crate}" crate.

%files       -n %{name}+parity-wasm-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages
which use "std" feature of "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+wasm-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+wasm-devel %{_description}

This package contains library source intended for building other packages
which use "wasm" feature of "%{crate}" crate.

%files       -n %{name}+wasm-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Thu Jan 30 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.12.0-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Fri Jul 26 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.12.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Tue May 07 15:33:29 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.12.0-1
- Update to 0.12.0

* Sat Apr 20 17:45:43 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.11.0-4
- Update goblin to 0.0.22

* Fri Apr 05 16:26:43 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.11.0-3
- Run tests in infrastructure

* Sat Feb 02 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.11.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_30_Mass_Rebuild

* Tue Nov 27 2018 Josh Stone <jistone@redhat.com> - 0.11.0-1
- Update to 0.11.0

* Tue Nov 13 2018 Josh Stone <jistone@redhat.com> - 0.10.0-2
- Adapt to new packaging

* Tue Oct 02 2018 Josh Stone <jistone@redhat.com> - 0.10.0-1
- Update to 0.10.0

* Sat Jul 28 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.9.0-2
- Bump goblin to 0.0.17

* Sat Jul 28 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.9.0-1
- Update to 0.9.0

* Sat Jul 14 2018 Fedora Release Engineering <releng@fedoraproject.org> - 0.7.0-6
- Rebuilt for https://fedoraproject.org/wiki/Fedora_29_Mass_Rebuild

* Mon Apr 23 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.7.0-5
- Bump goblin to 0.0.15

* Fri Feb 09 2018 Fedora Release Engineering <releng@fedoraproject.org> - 0.7.0-4
- Rebuilt for https://fedoraproject.org/wiki/Fedora_28_Mass_Rebuild

* Thu Jan 18 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.7.0-3
- Bump goblin to 0.0.14

* Mon Jan 08 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.7.0-2
- Rebuild for rust-packaging v5

* Mon Jan 01 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.7.0-1
- Update to 0.7.0

* Sun Dec 03 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.6.0-1
- Initial package
